import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// v32: PWA configuration.
//
// `registerType: 'autoUpdate'` makes the service worker pull a new bundle
// automatically when the rep returns to the app — they get the latest
// build without needing to hit reload. The auto-update reloads the page
// quietly on the next navigation; for an internal sales tool that's the
// least-friction posture.
//
// `workbox.navigateFallback` makes the SPA's hash-routed deep links work
// offline too — any in-app navigation falls back to index.html.
//
// Icons live in /public and get copied to /dist by Vite. The manifest is
// generated by the plugin (no separate manifest.json file needed).

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: [
        'favicon.svg',
        'apple-touch-icon.png',
        'icon-192.png',
        'icon-512.png',
        'icon-maskable.png',
      ],
      manifest: {
        name: 'Ronnoco Deal Builder',
        short_name: 'Deal Builder',
        description: 'Build deals, browse the catalog, and track submissions for the Ronnoco sales team.',
        // Same color the in-app navbar uses (navy-900). Drives the address bar
        // color on mobile when running as an installed PWA.
        theme_color: '#0A1F3D',
        background_color: '#FAFAF7',
        display: 'standalone',
        // Lock to portrait on phones; sales reps almost always use the app
        // one-handed. Desktop installs ignore this.
        orientation: 'portrait-primary',
        // Scope the PWA to the app root. start_url is the home route.
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: '/icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/icon-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            // Maskable icons let Android render the icon inside whatever
            // shape the launcher uses (circle, squircle, etc.) without
            // chopping off the artwork.
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // SPA fallback — any unmatched route hits index.html, which then
        // hash-routes client-side. Without this, deep links like
        // /#/quote/Q-2026-0007?t=xxx wouldn't work offline.
        navigateFallback: '/index.html',
        // Don't cache Supabase responses — always go to network for fresh data.
        // The shell HTML/JS/CSS are cached aggressively; data isn't.
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/[a-z]+\.supabase\.co\/.*/i,
            handler: 'NetworkOnly',
          },
        ],
      },
      // Don't auto-register the SW; we do it manually in main.jsx so we
      // can capture the beforeinstallprompt event for the in-app
      // "Install app" button on ProfilePage.
      injectRegister: null,
    }),
  ],
  server: {
    port: 5173,
  },
});
