import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

// v32 PWA bootstrap.
//
// Two responsibilities here, kept out of any component so they fire as
// early as possible in the page lifecycle:
//
//   1. Capture the `beforeinstallprompt` event when it fires (Chrome /
//      Edge / Android Chrome only — iOS and Firefox never fire it).
//      We stash the event on `window.__deferredInstallPrompt` and fire
//      a custom event so ProfilePage's InstallAppCard can light up its
//      "Install app" button. Without preventDefault() here, Chrome
//      would show its own mini-infobar — we prefer the in-app card.
//
//   2. Register the service worker (generated by vite-plugin-pwa) on
//      window load. The plugin generates `/sw.js` at build time;
//      runtime caching, auto-update behavior, and SPA navigation
//      fallback are all configured in vite.config.js.

if (typeof window !== 'undefined') {
  window.addEventListener('beforeinstallprompt', (event) => {
    event.preventDefault();
    window.__deferredInstallPrompt = event;
    window.dispatchEvent(new CustomEvent('pwa-install-available'));
  });

  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('/sw.js').catch(() => {
        // Service worker registration is best-effort. If it fails (older
        // browser, mixed-content issue, manifest typo) the app still
        // works fine — just no offline shell and no install prompt.
      });
    });
  }
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
